---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  creationTimestamp: "2024-04-13T08:27:25Z"
  labels:
    app.kubernetes.io/managed-by: crossplane
    app.kubernetes.io/name: basic
    component: network
    provider: aws
  name: vpc-network
spec:
  compositeTypeRef:
    apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
    kind: VpcNetwork
  mode: Pipeline
  pipeline:
  - step: create-subnetsets-from-template
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          #
          # Wait for the claim name to be populated before setting the appName
          #
          {{ $appName := "" }}
          {{ $claimRef := .observed.composite.resource.spec.claimRef }}
          {{ if not ( empty $claimRef ) }}
          {{ $appName = index $claimRef "name" }}
          {{ end }}

          #
          # Common information required from the composite
          #
          {{ $labels := .observed.composite.resource.metadata.labels }}
          {{ $region  := .observed.composite.resource.spec.region }}
          {{ $subnets := .observed.composite.resource.spec.subnets }}
          {{ $tags := .observed.composite.resource.spec.tags }}
          {{ $zones := .observed.composite.resource.spec.subnets.zones }}
          {{ $dp := .observed.composite.resource.spec.deletionPolicy }}

          #
          # Create public and private subnet sets
          #
          {{ $types := list "public" "private" }}
          {{ $zoneLen := len $zones }}

          #
          # Create one subnet set for each type (public / private)
          #
          {{ range $type := $types }}

          # Public subnets are the first 3 in the Cidr list from the claim
          {{ $cidrs := slice $subnets.cidrBlocks 0 $zoneLen }}

          {{ if eq $type "private" }}
          {{ $cidrs = slice $subnets.cidrBlocks $zoneLen (len $subnets.cidrBlocks) }}
          {{ end }}

          #
          #  Create SubnetSet for {{ $type }} subnets
          #
          ---
          apiVersion: xnetworks.crossplane.giantswarm.io/v1alpha1
          kind: SubnetSet
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: {{ $type }}-subnets
            labels:
              {{range $key, $value := $labels }}
              {{ $key }}: {{ $value }}
              {{ end }}
              visibility: {{ $type }}
          spec:
            claimRef:
            {{ range $key, $value := $claimRef }}
              {{ $key }}: {{ $value }}
            {{ end }}
            deletionPolicy: {{ $dp }}
            region: {{ $region }}
            subnets:
              a:
                zone: {{ index $zones 0 }}
                cidrBlock: {{ index $cidrs 0 }}
              b:
                zone: {{ index $zones 1 }}
                cidrBlock: {{ index $cidrs 1 }}
              c:
                zone: {{ index $zones 2 }}
                cidrBlock: {{ index $cidrs 2 }}
            type: {{ $type }}
            tags:
              {{ range $key, $value := $tags }}
              {{ $key }}: {{ $value }}
              {{ end }}
          {{ end }}

          #
          # Create nat gateways and elastic ips
          #
          {{ $index := 0 }}
          {{ $pubsubs := .observed.composite.resource.status.publicSubnets }}
          {{ $pubrtbls := .observed.composite.resource.status.publicRouteTables }}
          {{ $prirtbls := .observed.composite.resource.status.privateRouteTables }}
          {{ $igwId := .observed.composite.resource.status.igwId }}

          # Create EIP, NAT Gateway, and Route for each zone
          {{ range $k, $v := $zones }}


          {{ $az := printf "%s%s" $region $v }}
          {{ $pubsn := "" }}
          {{ $prirtbl := "" }}
          {{ $pubrtbl := "" }}

          # Get the public subnet ids when all 3 are created
          {{ if not (empty $pubsubs) }}
          {{ if eq (len (keys $pubsubs)) $zoneLen }}
          {{ $pubsn = get $pubsubs (index ( keys $pubsubs | sortAlpha ) $k) }}
          {{ end }}
          {{ end }}

          # Get the private route table ids when all 3 are created
          {{ if not (empty $prirtbls) }}
          {{ if eq (len ( keys $prirtbls )) $zoneLen }}
          {{ $prirtbl = get $prirtbls (index ( keys $prirtbls | sortAlpha ) $k) }}
          {{ end }}
          {{ end }}

          # Get the public route table ids when all 3 are created
          {{ if not (empty $pubrtbls) }}
          {{ if eq (len (keys $pubrtbls )) $zoneLen }}
          {{ $pubrtbl = get $pubrtbls (index ( keys $pubrtbls | sortAlpha ) $k) }}
          {{ end }}
          {{ end }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: EIP
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: eip-{{ $index }}
            labels:
              availabilityZone: {{ $az }}
              utilization: nat-gateway
          spec:
            forProvider:
              region: {{ $region }}
              domain: vpc
              tags:
                Name: {{ $appName }}-{{ $az }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: NATGateway
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: nat-gateway-{{ $index }}
            labels:
              availabilityZone: {{ $az }}
          spec:
            forProvider:
              region: {{ $region }}
              allocationIdSelector:
                matchControllerRef: true
                matchLabels:
                  availabilityZone: {{ $az }}
              subnetId: {{ if not (empty $pubsn) }}{{ $pubsn }}{{ end }}
              tags:
                Name: {{ $appName }}-{{ $az }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Route
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: ngw-route-{{ $index }}
            labels:
              availabilityZone: {{ $az }}
          spec:
            forProvider:
              destinationCidrBlock: 0.0.0.0/0
              natGatewayIdSelector:
                matchControllerRef: true
                matchLabels:
                  availabilityZone: {{ $az }}
              routeTableId: {{ if not (empty $prirtbl) }}{{ $prirtbl }}{{ end }}
              region: {{ $region }}
          ---
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: Route
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: igw-route-{{ $index }}
            labels:
              availabilityZone: {{ $az }}
          spec:
            forProvider:
              destinationCidrBlock: 0.0.0.0/0
              gatewayIdSelector:
                matchControllerRef: true
              routeTableId: {{ if not (empty $pubrtbl) }}{{ $pubrtbl }}{{ end }}
              region: {{ $region }}
          {{ $index = add $index 1 }}
          {{ end }}
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta2
      environment: null
      kind: Resources
      patchSets:
      - name: metadata
        patches:
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
          policy:
            toFieldPath: MergeObject
          type: FromCompositeFieldPath
        - fromFieldPath: spec.region
          toFieldPath: metadata.labels.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.providerConfigRef
          toFieldPath: spec.providerConfigRef
          type: FromCompositeFieldPath
      - name: commontags
        patches:
        - fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
          policy:
            toFieldPath: MergeObject
        - fromFieldPath: metadata.labels
          toFieldPath: spec.forProvider.tags
          type: FromCompositeFieldPath
          policy:
            toFieldPath: MergeObject
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.tags.region
      resources:

      # Create the VPC
      - name: basic-vpc
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: VPC
          spec:
            forProvider:
              enableDnsSupport: true
        patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - fromFieldPath: spec.vpcCidr
          toFieldPath: spec.forProvider.cidrBlock
          type: FromCompositeFieldPath

        - patchSetName: commontags
          type: PatchSet
        - fromFieldPath: spec.claimRef.name
          toFieldPath: spec.forProvider.tags.Name
          type: FromCompositeFieldPath
        - patchSetName: metadata
          type: PatchSet

        # patch vpcId back to the XR status
        - toFieldPath: status.id
          fromFieldPath: status.atProvider.id
          type: ToCompositeFieldPath

      # Take control of the default security group and block all traffic
      - name: default-sg
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: DefaultSecurityGroup
          spec:
            forProvider:
              vpcIdSelector:
                matchControllerRef: true
              # These are deliberately empty as we want to ensure that the
              # default security group blocks all traffic.
              ingress: []
              egress: []
        patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet

      # Create the Internet Gateway
      - name: basic-igw
        base:
          apiVersion: ec2.aws.upbound.io/v1beta1
          kind: InternetGateway
          spec:
            forProvider:
              vpcIdSelector:
                matchControllerRef: true
        patches:
        - fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
          type: FromCompositeFieldPath
        - patchSetName: commontags
          type: PatchSet
        - combine:
            variables:
            - fromFieldPath: spec.claimRef.name
            - fromFieldPath: spec.region
            strategy: string
            string:
              fmt: '%s-%s-vpc'
          toFieldPath: spec.forProvider.tags.Name
          type: CombineFromComposite
        - patchSetName: metadata
          type: PatchSet

        # patch igwId back to the XR status
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.internetGateway
          type: ToCompositeFieldPath

      # Patch information from the public subnets back to the XR status
      - name: public-subnets
        patches:
        - patchSetName: metadata
          type: PatchSet
        - fromFieldPath: status.id
          toFieldPath: spec.vpcId
          type: FromCompositeFieldPath

        - fromFieldPath: status.subnets.a
          toFieldPath: status.publicSubnets.a
          type: ToCompositeFieldPath
        - fromFieldPath: status.subnets.b
          toFieldPath: status.publicSubnets.b
          type: ToCompositeFieldPath
        - fromFieldPath: status.subnets.c
          toFieldPath: status.publicSubnets.c
          type: ToCompositeFieldPath

        - fromFieldPath: status.routeTables.a
          toFieldPath: status.publicRouteTables.a
          type: ToCompositeFieldPath
        - fromFieldPath: status.routeTables.b
          toFieldPath: status.publicRouteTables.b
          type: ToCompositeFieldPath
        - fromFieldPath: status.routeTables.c
          toFieldPath: status.publicRouteTables.c
          type: ToCompositeFieldPath

      # Patch information from the private subnets back to the XR status
      - name: private-subnets
        patches:
        - patchSetName: metadata
          type: PatchSet
        - fromFieldPath: status.id
          toFieldPath: spec.vpcId
          type: FromCompositeFieldPath

        - fromFieldPath: status.subnets.a
          toFieldPath: status.privateSubnets.a
          type: ToCompositeFieldPath
        - fromFieldPath: status.subnets.b
          toFieldPath: status.privateSubnets.b
          type: ToCompositeFieldPath
        - fromFieldPath: status.subnets.c
          toFieldPath: status.privateSubnets.c
          type: ToCompositeFieldPath

        - fromFieldPath: status.routeTables.a
          toFieldPath: status.privateRouteTables.a
          type: ToCompositeFieldPath
        - fromFieldPath: status.routeTables.b
          toFieldPath: status.privateRouteTables.b
          type: ToCompositeFieldPath
        - fromFieldPath: status.routeTables.c
          toFieldPath: status.privateRouteTables.c
          type: ToCompositeFieldPath

      # Patch the NAT gateway EIPs
      - name: eip-0
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet
      - name: eip-1
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet
      - name: eip-2
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet

      # Patch the NAT Gateways
      - name: nat-gateway-0
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.natGateways.a
          type: ToCompositeFieldPath
      - name: nat-gateway-1
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.natGateways.b
          type: ToCompositeFieldPath
      - name: nat-gateway-2
        patches:
        - patchSetName: commontags
          type: PatchSet
        - patchSetName: metadata
          type: PatchSet
        - fromFieldPath: status.atProvider.id
          toFieldPath: status.natGateways.c
          type: ToCompositeFieldPath

      # NGW Routes
      - name: ngw-route-0
        patches:
        - patchSetName: metadata
          type: PatchSet
      - name: ngw-route-1
        patches:
        - patchSetName: metadata
          type: PatchSet
      - name: ngw-route-2
        patches:
        - patchSetName: metadata
          type: PatchSet

      # IGW Routes
      - name: igw-route-0
        patches:
        - patchSetName: metadata
          type: PatchSet
      - name: igw-route-1
        patches:
        - patchSetName: metadata
          type: PatchSet
      - name: igw-route-2
        patches:
        - patchSetName: metadata
          type: PatchSet