---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: postgres-vnet
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: azure-account-creds
      key: credentials

