apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  name: example
spec:
  forProvider:
    containerAccessType: private
    storageAccountName: mystorageaccount
  providerConfigRef:
    name: azure-blob-storage
